name: publish
on:
  release:
    types: [published]
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: false
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          
      - name: build
        run: dotnet build

      - name: test
        run: dotnet test
        
      - name: publish Byndyusoft.Net.Http.ProtoBuf
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Net.Http.ProtoBuf/Byndyusoft.Net.Http.ProtoBuf.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Net.Http.Formatting.ProtoBuf
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Net.Http.Formatting.ProtoBuf/Byndyusoft.Net.Http.Formatting.ProtoBuf.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true